/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ziyad
 */
public class mainApp extends JFrame {
    /**
     * Creates new form mainApp
     */
    public mainApp() {
        initComponents();
        this.setTitle("Database App");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Departemen_btn = new javax.swing.JButton();
        Pengirim_btn = new javax.swing.JButton();
        Manager_btn = new javax.swing.JButton();
        Transaksi_btn = new javax.swing.JButton();
        Pembeli_btn = new javax.swing.JButton();
        Karyawan_btn = new javax.swing.JButton();
        Produk_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Setting_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Departemen_btn.setText("Departemen");
        Departemen_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Departemen_btnActionPerformed(evt);
            }
        });

        Pengirim_btn.setText("Pengirim");
        Pengirim_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pengirim_btnActionPerformed(evt);
            }
        });

        Manager_btn.setText("Manager");
        Manager_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_btnActionPerformed(evt);
            }
        });

        Transaksi_btn.setText("Transaksi");
        Transaksi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transaksi_btnActionPerformed(evt);
            }
        });

        Pembeli_btn.setText("Pembeli");
        Pembeli_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pembeli_btnActionPerformed(evt);
            }
        });

        Karyawan_btn.setText("Karyawan");
        Karyawan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Karyawan_btnActionPerformed(evt);
            }
        });

        Produk_btn.setText("Produk");
        Produk_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Produk_btnActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");

        Setting_btn.setText("Setting");
        Setting_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Setting_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Manager_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pengirim_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Departemen_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pembeli_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Karyawan_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Produk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Transaksi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Setting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Departemen_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pembeli_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pengirim_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Karyawan_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Manager_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Produk_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Transaksi_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Setting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Departemen_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Departemen_btnActionPerformed
        // TODO add your handling code here:
        Departemen gui=new Departemen(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Departemen_btnActionPerformed
public void back_to_menu(){
                mainApp.this.setVisible(true);
}
    private void Pembeli_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pembeli_btnActionPerformed
        // TODO add your handling code here:
        Pembeli gui=new Pembeli(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Pembeli_btnActionPerformed

    private void Pengirim_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pengirim_btnActionPerformed
        // TODO add your handling code here:
        Pengirim gui=new Pengirim(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Pengirim_btnActionPerformed

    private void Karyawan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Karyawan_btnActionPerformed
        // TODO add your handling code here:
        Karyawan gui=new Karyawan(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Karyawan_btnActionPerformed

    private void Manager_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_btnActionPerformed
        // TODO add your handling code here:
        Manager gui=new Manager(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Manager_btnActionPerformed

    private void Produk_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Produk_btnActionPerformed
        // TODO add your handling code here:
        Produk gui=new Produk(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Produk_btnActionPerformed

    private void Transaksi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transaksi_btnActionPerformed
        // TODO add your handling code here:
        Transaksi gui=new Transaksi(mainApp.this);
                gui.setVisible(true);
                dispose();
    }//GEN-LAST:event_Transaksi_btnActionPerformed

    private void Setting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Setting_btnActionPerformed
        // TODO add your handling code here:
        Driver gui=new Driver();
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_Setting_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainApp().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Departemen_btn;
    private javax.swing.JButton Karyawan_btn;
    private javax.swing.JButton Manager_btn;
    private javax.swing.JButton Pembeli_btn;
    private javax.swing.JButton Pengirim_btn;
    private javax.swing.JButton Produk_btn;
    private javax.swing.JButton Setting_btn;
    private javax.swing.JButton Transaksi_btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
